chore: fix audit findings
horse-link/contracts.horse.link pull request #130
Opened 2023-06-13 22:27 UTC by bitcoinbrisbane

[Link to ticket](url)

- One liner ticket title/description
- If not intuitive from the ticket -> short summary of code changes
- Include screenshots for visual UI changes

2023-06-13 22:31 UTC, brettvniekerk submitted a review, later dismissed

2023-06-14 22:35 UTC, bazmatic commented on tests/market.test.ts
> +	const LOOSER = 0x02;
```suggestion
	const LOSER = 0x02;
```

2023-06-14 22:41 UTC, bazmatic commented on tests/market.test.ts
> +			// add a looser result
```suggestion
			// add a loser result
```

2023-06-14 22:41 UTC, bazmatic commented on tests/market.test.ts
> +		it("Should not payout wage after timeout / expire has been reached and result added to the oracle", async () => {
```suggestion
		it("Should not payout wager after timeout / expire has been reached and result added to the oracle", async () => {
```

2023-06-14 22:43 UTC, bazmatic commented on tests/market.test.ts
> +				.withArgs(index, 272727300, LOOSER, vault.address);
```suggestion
				.withArgs(index, 272727300, LOSER, vault.address);
```

2023-06-14 22:48 UTC, bazmatic commented on tests/market.test.ts
> +			expect(await market.getTotalExposure()).to.equal(0);
Suggest checking the balance of the punter to show they didn't get paid, and/or balance of vault to show that they did.

2023-06-20 23:10 UTC, deBhal requested changes
Looks like the underlying code has changed to:  
_market.test.ts:1016_

> it("Should payout wage after timeout / expire has been reached", async () => {

but that the patch is still appropriate

2023-06-21 05:56 UTC, merged