HL-394
horse-link/contracts.horse.link pull request #75
Opened 2023-02-10 06:37 UTC by deBhal

[Link to ticket](https://dltx.atlassian.net/browse/HL-394)

Also addresses [HL-83](https://dltx.atlassian.net/browse/HL-83)

- One liner ticket title/description
- If not intuitive from the ticket -> short summary of code changes
- Include screenshots for visual UI changes

2023-02-12 23:43 UTC, bitcoinbrisbane commented on contracts/OddsLib.sol
> +        uint256 newMargin = targetMargin - PRECISION / scratchedOdds;
Should assert `scratchedOdds` is not equal to 0

2023-02-12 23:43 UTC, bitcoinbrisbane commented on contracts/OddsLib.sol
> +        uint256 total = 0;
Save some gas...

```suggestion
        uint256 total;
```

2023-02-12 23:44 UTC, bitcoinbrisbane commented on contracts/OddsLib.sol
> +        for (uint256 i = 0; i < odds.length; i++) {
Its better to "cache" this value, as reading the .length property uses more gas.

```suggestion
        uint256 count = odds.length;
        for (uint256 i = 0; i < count; i++) {
```

2023-02-12 23:45 UTC, bitcoinbrisbane commented on scripts/result.py
> +    response = requests.get('https://horse.link/api/config')
Check this link, it might be `https://alpha.horse.link/api/config` now.

2023-02-12 23:47 UTC, bitcoinbrisbane commented on contracts/Market.sol
> +		uint256 scratchedOdds = 0;
Gas saver...

```suggestion
		uint256 scratchedOdds;
```

2023-02-12 23:47 UTC, bitcoinbrisbane commented on contracts/Market.sol
> +		for (uint256 i = 0; i < result.scratched.length; i++) {
Same here with the .length.  Create a temp var to store length so the method costs less gas.

2023-02-12 23:52 UTC, bitcoinbrisbane requested changes
- Few solidity things to look at
- ~Check the URLs on the API~
- Check double line spacing on python between functions
- ~Bit of duplicate methods.~

2023-02-13 01:21 UTC, deBhal commented
I've refactored the shared .ts code and fixed up the `alpha.horse.link` url in `result.py`

2023-02-13 01:58 UTC, deBhal commented
I've fixed the https://alpha.horse.link url in the scripts directory as well as `contracts/Market.sol` and `tests/market.test.ts` because we change them in this PR, but there still are some stale references in the `deployments` directory:
`ag -l '\/\/horse.link'
```
deployments/goerli/DaiVault.json
deployments/goerli/DaiMarket.json
deployments/goerli/UsdtMarket.json
deployments/goerli/UsdtVault.json
```

2023-02-13 04:02 UTC, bitcoinbrisbane commented on contracts/OddsLib.sol
> +        return odds * PRECISION / margin;
Check != 0

2023-02-13 04:31 UTC, bitcoinbrisbane approved these changes

2023-02-14 23:44 UTC, bitcoinbrisbane requested changes
As discussed

2023-02-14 23:44 UTC, bitcoinbrisbane commented on contracts/Market.sol
> +		uint256 scratchCount = scratchedCount;
```suggestion
		uint256 scratchCount = result.scratched.length;
```

2023-02-14 23:44 UTC, bitcoinbrisbane commented on contracts/Market.sol
> +		uint256 originalOdds = _bets[index].payout / _bets[index].amount;
Checkout amount is not zero

2023-02-15 00:00 UTC, bitcoinbrisbane approved these changes

2023-02-15 07:16 UTC, merged